### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [joellecayen/canadamaps#1]
Email April 1:

canadianmaps has strong dependence on at least one of `rgdal`, `rgeos` or
`maptools`, but does not seem to use any functionality in code. The usage
may have been in `raster`, which now uses `terra` instead, or may be in
examples or vignettes. Please move all use of `rgdal`, `rgeos` or `maptools`
to Suggests: and protect any use against these packages not being present.
The packages will be archived in October 2023. See
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and perhaps
view
https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_Y
mAh4pq9&index=1.

See also https://r-spatial.org/r/2023/04/10/evolution3.html, please fix best by June, latest October 2023.

**Comment by rsbivand** [comment]
Only three months remain to save this package from failure. Please act now!

**Comment by joellecayen** [comment]
Removed rgdal from imports and resubmitted to CRAN

**Comment by rsbivand** [comment]
Great, thanks!
